version: 2.1
orbs:
  python: circleci/python@2
  docker: circleci/docker@1.7.0
jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run tests
          command: pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
  build-and-push-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t $DOCKERHUB_USERNAME/fastapiv2:${CIRCLE_SHA1} .
            docker push $DOCKERHUB_USERNAME/fastapiv2:${CIRCLE_SHA1}
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test-python
      - build-and-push-docker:
          requires:
            - test-python
