version: 2.1
orbs:
  python: circleci/python@2
  docker: circleci/docker@1.7.0
  ssh: circleci/ssh@1.0.3  # Use the SSH orb
jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run tests
          command: pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
  build-and-push-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t $DOCKERHUB_USERNAME/fastapiv2:test_cd .
            docker push $DOCKERHUB_USERNAME/fastapiv2:test_cd
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - ssh/remote:
          name: Deploy Application
          remote_host: "18.226.180.175"
          command: |
            sudo docker pull akashjanardhan/fastapiv2:test_cd
            sudo docker stop my-fastapi-app || true
            sudo docker rm my-fastapi-app || true
            sudo docker run -d --name my-fastapi-app -p 80:80 akashjanardhan/fastapiv2:test_cd
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test-python
      - build-and-push-docker:
          requires:
            - test-python
      - deploy:
          requires:
            - build-and-push-docker
