version: 2.1
orbs:
  python: circleci/python@2
  docker: circleci/docker@1.7.0
jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run tests
          command: pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
  build-and-push-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t $DOCKERHUB_USERNAME/fastapiv2:test_cd .
            docker push $DOCKERHUB_USERNAME/fastapiv2:test_cd
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2048 SHA256:8XaZGPwgBw6qCSuly+W0f29rMp7x6G0SFIDs0ZBK/jU no comment (RSA)"
      - run:
          name: Deploy Application
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@18.226.180.175 \<< EOF
              sudo docker pull akashjanardhan/fastapiv2:test_cd
              sudo docker stop my-fastapi-app || true
              sudo docker rm my-fastapi-app || true
              sudo docker run -d --name my-fastapi-app -p 80:80 akashjanardhan/fastapiv2:test_cd
            EOF
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test-python
      - build-and-push-docker:
          requires:
            - test-python
      - deploy:
          requires:
            - build-and-push-docker
